NoPermission: You must be an administrator or own the object to access this page!

Welcome: Welcome!
Instructions: Welcome to the MadLib Factory. To get started, login and go to the lib listing. In the 'New' section, name your MadLib and write it in HTML. Use the format [s:part_of_speech] for single placeholders and [m:name] for multi placeholders which will be replaced by a constant value. To play a MadLib, just fill in the values in the Play form on the MadLib page.

NoLibs: No MadLibs exist yet!

NewMadLib: New
NewMadLibTitle: Title
NewMadLibContents: Contents
NewMadLibSubmit: Create!

MadLibCreated name@Text: "#{name}" created.
MadLibDeleted name@Text: "#{name}" deleted.

Singles: Singles
Multies: Multies
PlaySubmit: Interpolate!

Play name@Text: Playing "#{name}"
PlayInvalid: Correct your form. See below for more details.
Results name@Text: Results for "#{name}"
Again: Play Again

Posted email@Text t@UTCTime: Posted by #{email} at #{formatTime defaultTimeLocale (dateTimeFmt defaultTimeLocale) t}
PostedTime t@UTCTime: Posted at #{formatTime defaultTimeLocale (dateTimeFmt defaultTimeLocale) t}

ListTitle: All the MadLibs!
