NoPermission: No tenes permiso para ver ese pagina.

Welcome: ¡Bienvenido!
Instructions: Bienvenido al MadLib Factory. Para empezar, ve la lista de los libs. In el seccion, 'Nuevo,' nombra su MadLib y escribe el contenido en HTML. Usa el formato [s:parte_de_la_oración] para marcadores de posición individuales y el formato [m:nombre] para marcadores de posición que vas usar varios veces. Para jugar, llena los espacios en blanco en el formulario y empuja el botón que dice "¡Interpolar!"

NoLibs: ¡No hay ningunos MadLibs!

NewMadLib: Nuevo
NewMadLibTitle: Titulo
NewMadLibContents: Contentenido
NewMadLibSubmit: ¡Crear!

MadLibCreated name: "#{name}" fue creado.
MadLibDeleted name: "#{name}" fue eliminado.

Singles: Individuales
Multies: Múltiples
PlaySubmit: ¡Interpolar!

Play name: Jugando "#{name}"
PlayInvalid: Corrija el formulario.
Results name: Resultados para "#{name}"
Again: Otra vez!

Posted email t: #{email} publicó este MadLib por #{formatTime defaultTimeLocale (dateTimeFmt defaultTimeLocale) t}
PostedTime t: Policado por #{formatTime defaultTimeLocale (dateTimeFmt defaultTimeLocale) t}

ListTitle: Todos los MadLibs
